"""Presentation-first PaySim dashboard, with readable labels and genuine ML evidence.

Training is a separate, reproducible task. The app loads saved fitted pipelines,
full later-period evaluation scores, and actual SHAP explanations on demand.
"""
from __future__ import annotations

import html
import os
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from presentation_core import (
    DISPLAY_NAMES, FEATURE_GLOSSARY, FEATURES, RAW_FIELDS,
    PresentationBundle, engineer_features, evaluate_scores, load_bundle,
    score_transactions,
)

ROOT = Path(__file__).resolve().parent
TABS = (
    "Overview", "Data Explorer", "Model Performance", "Explainability",
    "Live Predictor", "Methodology", "Glossary",
    "Check a card payment", "How it works & results",
)
MINT, ROSE, LILAC, TEXT, MUTED = "#73E5BC", "#FF7F98", "#A594FF", "#E7EEF8", "#99A9BE"
TYPE_LABELS = {"PAYMENT": "Payment", "TRANSFER": "Transfer", "CASH_OUT": "Cash withdrawal", "CASH_IN": "Cash deposit", "DEBIT": "Debit"}
METRIC_HELP = {
    "precision": "Of the transactions flagged for review, the fraction that really were fraud in the recorded dataset. More false alarms lower precision.",
    "recall": "Of all recorded fraud cases, the fraction the model flagged. Missed fraud lowers recall.",
    "f1": "A single score balancing precision and recall. Both must be useful for a high F1 score.",
    "pr_auc": "Area under the precision–recall curve across all thresholds, calculated by trapezoidal integration of the full curve. Larger is better. Average precision is saved separately and uses a different step-wise summary.",
    "roc_auc": "How well the scores rank fraud above legitimate transactions across all thresholds. 0.5 resembles random ranking; 1.0 is perfect ranking.",
    "accuracy": "The fraction of all predictions that are correct. Since fraud is rare, always predicting legitimate can produce high accuracy while detecting no fraud.",
}
TERM_GLOSSARY = {
    "Precision": "Among the payments flagged as suspicious, how many actually were fraud? High precision means fewer false alarms.",
    "Recall": "Among all fraud payments, how many did the system catch? High recall means fewer missed fraud cases.",
    "F1 score": "A balanced combination of precision and recall; it falls when either one is poor.",
    "PR-AUC": "The area under the precision–recall curve as the decision threshold changes. This project calculates the actual curve area using trapezoids; higher is better.",
    "Average precision": "A related precision–recall summary that adds precision values weighted by changes in recall. It can differ from PR-AUC; the project saves both rather than treating them as identical.",
    "ROC-AUC": "How well the model puts fraud above legitimate payments in its score ranking. It considers all thresholds.",
    "Confusion matrix": "A table counting correct legitimate decisions, caught fraud, false alarms, and missed fraud.",
    "Threshold": "The minimum model fraud score needed to flag a transaction for review. Lower values usually catch more fraud and create more false alarms.",
    "Class imbalance": "One category is much rarer than the other. Here legitimate transactions greatly outnumber fraud, so accuracy alone is misleading.",
    "SHAP": "A method that divides a model's prediction into feature contributions. Positive contributions raise the fraud score; negative ones lower it. It explains the model, not the cause of a crime.",
    "XGBoost": "A sequence of decision trees that learn to correct the earlier trees' mistakes. Their combined output produces the fraud score.",
    "Random Forest": "Many decision trees trained with varied data and features. Their predictions are combined to reduce the reliance on any one tree.",
    "Logistic Regression": "A simple baseline that learns a weighted combination of input features and turns it into a score between zero and one.",
    "One-hot encoding": "A separate yes/no column for each transaction type. It lets the model use categories without pretending they have a numeric order.",
    "Synthetic dataset": "Transactions generated by a simulator rather than copied from customers' real bank statements.",
    "Validation data": "A middle time period used to choose the model and its decision threshold. It is separate from the final test period.",
    "Test data": "Later transactions used to measure the chosen model's performance. The headline results use the full, naturally imbalanced test period.",
    "Fraud probability": "The model's estimated fraud score between zero and one. It has not been separately calibrated to real banking fraud rates, so 80% is not a guarantee that eight of ten such payments are fraud.",
}
PRESENTATION_CSS = """
.presentation-hero{position:relative;overflow:hidden;border:1px solid var(--cv-border);border-radius:22px;
 padding:32px 35px;margin:15px 0 24px;background:radial-gradient(ellipse at 92% 30%,rgba(115,229,188,.14),transparent 55%),#111A2B;
 animation:cv-reveal .6s var(--cv-ease) backwards;}
.presentation-hero h1{max-width:760px;font-size:clamp(1.9rem,3vw,2.9rem);line-height:1.15;margin:0 0 14px;padding:0;}
.presentation-hero p{max-width:790px;color:#AABBD2;line-height:1.8;margin:0;}
.presentation-chips{display:flex;gap:9px;flex-wrap:wrap;margin-top:21px;}
.presentation-chips span{font-size:.68rem;padding:6px 10px;border:1px solid rgba(115,229,188,.2);border-radius:7px;color:#BDE5D7;}
.presentation-step{border:1px solid var(--cv-border);border-radius:15px;padding:22px;min-height:156px;background:rgba(17,26,43,.8);
 animation:cv-reveal .5s var(--cv-ease) backwards;}
.presentation-step strong{color:#E7EEF8;font-size:.91rem;display:block;margin:9px 0;}
.presentation-step p{font-size:.78rem;color:#99A9BE;line-height:1.7;margin:0;}
.presentation-step .step-index{color:#73E5BC;font-size:.7rem;letter-spacing:.14em;}
.risk-result{padding:24px;border:1px solid var(--cv-border);border-left:4px solid #73E5BC;border-radius:15px;
 background:linear-gradient(100deg,rgba(115,229,188,.08),#111A2B);animation:cv-reveal .4s var(--cv-ease) backwards;}
.risk-result.high{border-left-color:#FF7F98;background:linear-gradient(100deg,rgba(255,127,152,.1),#111A2B);}
.risk-result.medium{border-left-color:#A594FF;background:linear-gradient(100deg,rgba(165,148,255,.1),#111A2B);}
.risk-result strong{display:block;font-size:1.3rem;margin:5px 0 9px;}.risk-result p{color:#B1BFD2;font-size:.82rem;line-height:1.7;margin:0;}
[data-testid="stTabs"] [role="tablist"]{gap:7px;padding-bottom:9px;overflow-x:auto;}
[data-testid="stTabs"] [role="tab"]{white-space:nowrap;border-radius:9px;padding:10px 15px;font-size:.8rem;transition:background .2s ease;}
[data-testid="stTabs"] [role="tab"][aria-selected="true"]{background:rgba(115,229,188,.1);}
@media(max-width:700px){.presentation-hero{padding:24px}.presentation-step{min-height:0;padding:18px}[data-testid="stTabs"] [role="tab"]{padding:9px 11px}}
@media(prefers-reduced-motion:reduce){.presentation-hero,.presentation-step,.risk-result{animation:none!important}[data-testid="stTabs"] [role="tab"]{transition:none!important}}
"""


def artifact_directory() -> Path:
    return Path(os.environ.get("PRESENTATION_ARTIFACT_DIR", str(ROOT / "presentation_artifacts"))).resolve()


def file_signature(directory: Path, names: tuple[str, ...]) -> tuple:
    result = []
    for name in names:
        try:
            stat = (directory / name).stat()
            result.append((name, stat.st_size, stat.st_mtime_ns))
        except OSError:
            result.append((name, -1, -1))
    return tuple(result)


@st.cache_resource(show_spinner="Loading the trained presentation model…")
def cached_bundle(directory: str, signature: tuple) -> PresentationBundle:
    return load_bundle(Path(directory))


@st.cache_data(show_spinner="Loading the transaction sample…")
def cached_data(path: str, signature: tuple) -> pd.DataFrame:
    frame = pd.read_parquet(path) if Path(path).suffix == ".parquet" else pd.read_csv(path, float_precision="round_trip")
    if frame.empty:
        raise ValueError("The saved transaction sample is empty.")
    if not set(RAW_FIELDS).issubset(frame.columns) or "isFraud" not in frame:
        raise ValueError("The saved sample is missing required payment details or recorded labels.")
    if not frame["isFraud"].isin([0, 1]).all():
        raise ValueError("The saved sample has invalid recorded fraud labels.")
    return frame


@st.cache_data(show_spinner=False)
def cached_scores(path: str, signature: tuple) -> dict[str, np.ndarray]:
    with np.load(path, allow_pickle=False) as saved:
        arrays = {name: saved[name] for name in saved.files}
    if "labels" not in arrays or arrays["labels"].size == 0:
        raise ValueError("The saved evaluation scores are empty or incomplete.")
    return arrays


def what_am_i_looking_at(text: str) -> None:
    """Every page starts with the same discoverable, plain-English explanation."""
    with st.expander("What am I looking at?"):
        st.write(text)


def heading(title: str, description: str, kicker: str = "Presentation workspace") -> None:
    st.markdown(
        '<div class="page-intro"><div class="eyebrow">' + html.escape(kicker) + '</div><h1>'
        + html.escape(title) + '</h1><p class="muted">' + html.escape(description) + '</p></div>',
        unsafe_allow_html=True,
    )


def style_chart(figure: go.Figure, height: int = 330) -> go.Figure:
    figure.update_layout(template="plotly_dark", paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                         font=dict(color=TEXT, family="Inter, sans-serif", size=12), height=height,
                         margin=dict(l=16, r=16, t=35, b=42), colorway=[MINT, ROSE, LILAC],
                         legend=dict(orientation="h", y=1.12))
    figure.update_xaxes(gridcolor="rgba(153,169,190,.1)")
    figure.update_yaxes(gridcolor="rgba(153,169,190,.1)")
    return figure


def model_records(metadata: dict) -> list[dict]:
    models = metadata["models"]
    return [{"name": name, **record} for name, record in models.items()] if isinstance(models, dict) else models


def selected_record(bundle: PresentationBundle) -> dict:
    return next(record for record in model_records(bundle.metadata) if record["name"] == bundle.metadata["selected_model"])


def default_threshold(bundle: PresentationBundle) -> float:
    return float(bundle.metadata["threshold"])


def friendly_frame(frame: pd.DataFrame) -> pd.DataFrame:
    """Never leak dataset keys or account identifiers through tables."""
    result = frame.loc[:, [name for name in frame if name in DISPLAY_NAMES]].copy()
    if "type" in result:
        result["type"] = result["type"].map(TYPE_LABELS).fillna("Other")
    if "isFraud" in result:
        result["isFraud"] = result["isFraud"].map({0: "Legitimate", 1: "Fraud"})
    if "prediction" in result:
        result["prediction"] = result["prediction"].map({0: "Not flagged", 1: "Flagged for review"})
    if "account_emptied" in result:
        result["account_emptied"] = result["account_emptied"].map({0: "No", 1: "Yes"})
    return result.rename(columns=DISPLAY_NAMES)


def model_metrics(metrics: dict) -> None:
    """All metric cards have explanations; accuracy stays a secondary measure."""
    columns = st.columns(3)
    for index, (label, key) in enumerate((("Precision", "precision"), ("Recall", "recall"), ("F1 score", "f1"),
                                         ("PR-AUC", "pr_auc"), ("ROC-AUC", "roc_auc"))):
        value = f"{float(metrics[key]):.8f}" if key in ("pr_auc", "roc_auc") else f"{float(metrics[key]):.2%}"
        columns[index % 3].metric(label, value, help=METRIC_HELP[key])


def _data(bundle: PresentationBundle, filename: str = "sample_data.parquet") -> pd.DataFrame:
    return cached_data(str(bundle.directory / filename), file_signature(bundle.directory, (filename,)))


def overview_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("This is an academic machine-learning demonstration that learns patterns in simulated financial transactions. You can inspect the data, test a payment, and see both the model's reasoning and its measured mistakes. PaySim simulates mobile-money transfers, so it is a financial-fraud proxy rather than real credit-card network data.")
    metadata, dataset = bundle.metadata, bundle.metadata["dataset"]
    st.markdown(
        '<div class="presentation-hero"><div class="eyebrow">CreditVault · explainable machine learning</div>'
        '<h1>Credit Card Fraud<br>Detection System</h1>'
        '<p>A presentation-ready financial fraud project. Readable payment details become useful signals; a trained model estimates risk, and SHAP explains its decision in plain English.</p>'
        '<div class="presentation-chips"><span>PaySim · simulated financial data</span><span>'
        + html.escape(str(metadata["selected_model"])) + '</span><span>Later-period evaluation</span><span>Real SHAP explanations</span></div></div>',
        unsafe_allow_html=True,
    )
    total = int(dataset.get("total_transactions", dataset.get("rows", 0)))
    fraud = int(dataset["fraud_count"])
    sample = int(metadata["sampling"]["rows"])
    columns = st.columns(4)
    for column, label, value, help_text in zip(columns,
        ("Source transactions", "Recorded fraud", "Source fraud rate", "Project sample"),
        (f"{total:,}", f"{fraud:,}", f"{fraud / total:.3%}", f"{sample:,}"),
        ("All transactions in the verified original PaySim source before sampling.",
         "Every recorded fraud row in the source is retained in the project sample.",
         "Fraud cases divided by all original source transactions. This is the natural simulated rate, before fraud-enriched sampling.",
         "All source fraud cases plus legitimate transactions stratified by time period and transaction type. The sample is intentionally more fraud-enriched than the source.")):
        column.metric(label, value, help=help_text)
    st.info("Two populations are kept separate: Data Explorer shows the fraud-enriched project sample; headline model metrics use every transaction in the full later test period.")
    left, right = st.columns([1, 1.1], gap="large")
    with left:
        st.subheader("Why fraud needs special attention")
        chart = go.Figure(go.Bar(x=["Legitimate", "Fraud"], y=[total - fraud, fraud], marker_color=[MINT, ROSE],
                                text=[f"{total - fraud:,}", f"{fraud:,}"], textposition="outside"))
        chart.update_yaxes(title="Source transactions", type="log")
        st.plotly_chart(style_chart(chart, 290), width="stretch", key="presentation_distribution")
        st.caption("The vertical axis uses a logarithmic scale so both classes remain visible. Fraud is very rare; accuracy alone can hide a model that misses every fraud case.")
    with right:
        st.subheader("What the system actually does")
        st.write("**1. Read a transaction.** Amount, transaction type, sender/receiver balances, and observed account activity.")
        st.write("**2. Calculate understandable signals.** Did money leave and arrive as expected? Was the sender account emptied? How active was the account recently?")
        st.write("**3. Score with a trained model.** The fitted classifier estimates a fraud score and compares it with a validation-selected threshold.")
        st.write("**4. Explain and review.** SHAP describes which inputs raised or lowered the model's score. A flag requests review; it does not prove fraud.")
    st.caption("This demonstration does not connect to a bank, block payments, or determine a person's intent. Recorded balances after a payment make the PaySim task retrospective; they are not normally available before authorizing a payment.")


def data_explorer_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("Explore the real saved project sample, with readable column names and filters. It keeps every source fraud row, so fraud appears more often here than in the original source. Charts describe data patterns; a correlation does not prove what caused fraud.")
    heading("Data Explorer", "Know the data before explaining the model.")
    data = _data(bundle)
    columns = st.columns(3)
    classes = columns[0].multiselect("Recorded outcome", ["Legitimate", "Fraud"], default=["Legitimate", "Fraud"], key="presentation_filter_class")
    types = columns[1].multiselect(DISPLAY_NAMES["type"], sorted(data["type"].unique()), default=sorted(data["type"].unique()), format_func=lambda key: TYPE_LABELS.get(key, key.title()), key="presentation_filter_type")
    maximum = columns[2].number_input("Maximum Transaction Amount", min_value=0.0, value=float(data["amount"].max()), step=1000.0, help="Show transactions whose recorded amount is at or below this value. PaySim currency units are not converted to another currency.")
    labels = [value for text, value in (("Legitimate", 0), ("Fraud", 1)) if text in classes]
    filtered = data.loc[data["isFraud"].isin(labels) & data["type"].isin(types) & data["amount"].le(maximum)]
    counts = st.columns(3)
    counts[0].metric("Matching transactions", f"{len(filtered):,}", help="The number of sample transactions left after applying your filters.")
    counts[1].metric("Recorded fraud", f"{int(filtered['isFraud'].sum()):,}", help="Recorded fraud cases among the filtered sample transactions.")
    counts[2].metric("Filtered fraud share", f"{filtered['isFraud'].mean():.2%}" if len(filtered) else "—", help="Fraud cases divided by the filtered transaction count. This is the sample's share, not the natural population fraud rate.")
    if filtered.empty:
        st.info("No transactions match these filters. Choose at least one outcome and transaction type, or increase the amount limit.")
        return
    st.subheader("Transaction preview")
    preview_size = st.select_slider("Rows to preview", options=[10, 25, 50, 100], value=10, key="presentation_preview_size")
    st.dataframe(friendly_frame(filtered.head(preview_size)), hide_index=True, width="stretch")
    with st.expander("What does each displayed column mean?"):
        st.dataframe(pd.DataFrame([{"Column": DISPLAY_NAMES[name], "Plain meaning": FEATURE_GLOSSARY.get(name, "A saved model output or recorded outcome.")} for name in filtered if name in DISPLAY_NAMES]), hide_index=True, width="stretch")
    left, right = st.columns(2)
    with left:
        st.subheader("Transaction types and recorded outcomes")
        chart = go.Figure()
        type_order = sorted(filtered["type"].unique())
        for label, value, color in (("Legitimate", 0, MINT), ("Fraud", 1, ROSE)):
            counts_by_type = filtered.loc[filtered.isFraud.eq(value), "type"].value_counts()
            chart.add_bar(name=label, x=[TYPE_LABELS.get(kind, kind.title()) for kind in type_order], y=[int(counts_by_type.get(kind, 0)) for kind in type_order], marker_color=color)
        chart.update_layout(barmode="group")
        chart.update_yaxes(title="Sample transaction count", type="log")
        st.plotly_chart(style_chart(chart), width="stretch", key="presentation_type_distribution")
        st.caption("Counts use a logarithmic axis. An empty bar means no matching rows for that outcome and type.")
    with right:
        st.subheader("Transaction amounts")
        positive_max = max(float(filtered["amount"].max()), 1.0)
        bins = np.geomspace(0.01, max(positive_max, 0.011), 36)
        centers = np.sqrt(bins[:-1] * bins[1:])
        chart = go.Figure()
        for label, value, color in (("Legitimate", 0, MINT), ("Fraud", 1, ROSE)):
            histogram, _ = np.histogram(np.maximum(filtered.loc[filtered.isFraud.eq(value), "amount"].to_numpy(), 0.01), bins=bins)
            share = histogram / max(int(histogram.sum()), 1)
            chart.add_trace(go.Scatter(x=centers, y=share, name=label, mode="lines", line=dict(color=color, width=2.5)))
        chart.update_xaxes(title=DISPLAY_NAMES["amount"], type="log")
        chart.update_yaxes(title="Share within each recorded class", tickformat=".0%")
        st.plotly_chart(style_chart(chart), width="stretch", key="presentation_amount_distribution")
        st.caption("Amount bins use a logarithmic scale. Each outcome is normalized separately; this compares amount patterns rather than class size.")
    st.subheader("Activity across the day")
    hours = filtered.assign(_hour=filtered["step"] % 24).groupby(["_hour", "isFraud"]).size().unstack(fill_value=0)
    chart = go.Figure()
    for label, value, color in (("Legitimate", 0, MINT), ("Fraud", 1, ROSE)):
        chart.add_trace(go.Scatter(x=hours.index, y=hours.get(value, pd.Series(0, index=hours.index)), name=label, mode="lines+markers", line=dict(color=color)))
    chart.update_xaxes(title=DISPLAY_NAMES["hour_of_day"], dtick=3)
    chart.update_yaxes(title="Sample transaction count", type="log")
    st.plotly_chart(style_chart(chart, 280), width="stretch", key="presentation_hour_distribution")
    st.caption("PaySim has no transaction-duration column. Timing is represented by Hour of Day and earlier sender activity; hour numbers are derived from the simulator's hour counter.")
    with st.expander("Correlation heatmap · numeric features"):
        features = engineer_features(filtered.loc[:, list(RAW_FIELDS)])
        numeric = features.select_dtypes(include="number").copy()
        numeric["isFraud"] = filtered["isFraud"].to_numpy()
        correlation = numeric.corr().rename(index=DISPLAY_NAMES, columns=DISPLAY_NAMES)
        chart = go.Figure(go.Heatmap(z=correlation.to_numpy(), x=list(correlation.columns), y=list(correlation.index), zmin=-1, zmax=1,
                                    colorscale=[[0, LILAC], [.5, "#111A2B"], [1, MINT]], colorbar=dict(title="Correlation"),
                                    hovertemplate="%{y}<br>%{x}: %{z:.2f}<extra></extra>"))
        chart.update_layout(margin=dict(l=10, r=10, t=20, b=180))
        st.plotly_chart(style_chart(chart, 650), width="stretch", key="presentation_correlation")
        st.caption("Values near +1 move together; values near −1 move in opposite directions. Missing cells mean a feature had no variation in this filtered data. Labels are included only for exploration, never as model inputs.")


def model_performance_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("These are measured results on all transactions in the later test period, rather than a balanced demonstration sample. Move the decision threshold to see the real tradeoff between catching fraud and creating false alarms. The slider explores the saved model; it does not retrain or choose a new best model.")
    heading("Model Performance", "Show useful evidence, not just a high accuracy number.")
    record = selected_record(bundle)
    arrays = cached_scores(str(bundle.directory / "evaluation_scores.npz"), file_signature(bundle.directory, ("evaluation_scores.npz",)))
    labels, scores = arrays["labels"], arrays[record["score_array_key"]]
    st.caption(f"Deployed model: {bundle.metadata['selected_model']}. Model and default threshold were chosen using the earlier validation period. Evaluation population: {len(labels):,} later transactions, including {int(labels.sum()):,} recorded fraud cases.")
    threshold = st.slider("Decision threshold · flag when the fraud score reaches this value", min_value=0.0, max_value=1.0,
                          value=default_threshold(bundle), step=0.001, format="%.3f", key="presentation_threshold",
                          help="Lower thresholds usually catch more fraud and raise more false alarms. This slider recomputes predictions from saved scores on the full test period; the trained model is unchanged.")
    st.caption(f"Saved validation-selected threshold: {default_threshold(bundle):.6f}. Current exploratory threshold: {threshold:.6f}.")
    metrics = evaluate_scores(labels, scores, threshold)
    model_metrics(metrics)
    matrix = np.asarray(metrics["confusion_matrix"], dtype=int)
    left, right = st.columns([1, 1.15], gap="large")
    with left:
        st.subheader("Confusion matrix · count every mistake")
        chart = go.Figure(go.Heatmap(z=matrix, x=["Not flagged", "Flagged for review"], y=["Recorded legitimate", "Recorded fraud"],
                                    text=matrix, texttemplate="%{text:,}", colorscale=[[0, "#111A2B"], [1, MINT]], showscale=False,
                                    hovertemplate="%{y}<br>%{x}: %{z:,}<extra></extra>"))
        chart.update_yaxes(autorange="reversed")
        st.plotly_chart(style_chart(chart, 300), width="stretch", key="presentation_confusion_matrix")
        st.write(f"**{matrix[1, 1]:,} fraud cases caught** · **{matrix[1, 0]:,} fraud cases missed**  \n**{matrix[0, 1]:,} false alarms** · **{matrix[0, 0]:,} correct legitimate decisions**")
    with right:
        st.subheader("Precision–recall curve")
        curve = metrics["pr_curve"]
        chart = go.Figure(go.Scatter(x=curve["recall"], y=curve["precision"], mode="lines", line=dict(color=MINT, width=3), name=bundle.metadata["selected_model"]))
        chart.add_hline(y=float(labels.mean()), line_dash="dot", line_color=MUTED)
        chart.update_xaxes(title="Recall · fraction of fraud caught", range=[0, 1], tickformat=".0%")
        chart.update_yaxes(title="Precision · fraction of flags that are fraud", range=[0, 1.03], tickformat=".0%")
        st.plotly_chart(style_chart(chart, 300), width="stretch", key="presentation_pr_curve")
        st.caption("The dotted line is the natural test-period fraud rate. PR-AUC is the actual area under the full precision–recall curve, using trapezoidal integration; it is independent of the current slider threshold. Average precision is a separate, step-wise summary.")
    st.subheader("Three trained models · same later test period")
    rows = []
    for candidate in model_records(bundle.metadata):
        result = candidate["test"]
        rows.append({"Model": candidate["name"] + (" · deployed" if candidate["name"] == bundle.metadata["selected_model"] else ""),
                     "Precision": result["precision"], "Recall": result["recall"], "F1 score": result["f1"],
                     "PR-AUC": result["pr_auc"], "ROC-AUC": result["roc_auc"],
                     "Validation-selected threshold": candidate["threshold"]})
    st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch", column_config={name: st.column_config.NumberColumn(format="%.8f" if name in ("PR-AUC", "ROC-AUC") else "percent", help="Full later test-period result at this model's own validation-selected threshold.") for name in ("Precision", "Recall", "F1 score", "PR-AUC", "ROC-AUC")})
    st.caption("This table keeps each model's saved validation-selected threshold. Only the deployed model's cards and confusion matrix respond to the slider. Test scores did not select the winning model.")
    with st.expander("Why accuracy is not the headline metric"):
        columns = st.columns(2)
        columns[0].metric("Accuracy at current threshold", f"{metrics['accuracy']:.2%}", help=METRIC_HELP["accuracy"])
        columns[1].metric("Always-legitimate baseline", f"{1 - labels.mean():.2%}", help="Accuracy from predicting every payment as legitimate. This baseline catches zero fraud; it shows why a high accuracy figure can be misleading.")
        st.write("Fraud is rare. A classifier can look accurate by ignoring it. Precision tells us whether review alerts are useful, recall tells us how much fraud is caught, and F1 and PR-AUC summarize the tradeoff.")
    with st.expander("ROC curve · another view of the ranking"):
        curve = metrics["roc_curve"]
        chart = go.Figure(go.Scatter(x=curve["fpr"], y=curve["tpr"], mode="lines", line=dict(color=LILAC, width=3), name=bundle.metadata["selected_model"]))
        chart.add_shape(type="line", x0=0, y0=0, x1=1, y1=1, line=dict(color=MUTED, dash="dot"))
        chart.update_xaxes(title="False-positive rate · legitimate payments flagged", range=[0, 1], tickformat=".0%")
        chart.update_yaxes(title="True-positive rate · recall", range=[0, 1], tickformat=".0%")
        st.plotly_chart(style_chart(chart, 330), width="stretch", key="presentation_roc_curve")
        st.caption("The diagonal represents random ranking. ROC-AUC is useful, but PR-AUC and actual false-alarm counts are especially relevant when fraud is rare.")


def _shap_figure(explanation: Any, *, global_plot: bool = False) -> None:
    """Render the genuine SHAP Explanation, keeping all feature labels readable."""
    import matplotlib.pyplot as plt
    import shap
    with plt.rc_context({"figure.facecolor": "#111A2B", "axes.facecolor": "#111A2B", "text.color": TEXT,
                         "axes.labelcolor": TEXT, "xtick.color": TEXT, "ytick.color": TEXT,
                         "axes.edgecolor": MUTED, "font.size": 11}):
        if global_plot:
            shap.plots.beeswarm(explanation, max_display=15, show=False, plot_size=(10, 7))
        else:
            shap.plots.waterfall(explanation, max_display=12, show=False)
        figure = plt.gcf()
        st.pyplot(figure, width="stretch")
        plt.close(figure)


def shap_contribution_table(explanation: Any, bundle: PresentationBundle) -> None:
    """Readable numbers let a presenter verify the waterfall's additive meaning."""
    from presentation_explain import explanation_output_unit
    values = np.asarray(explanation.values, dtype=float).reshape(-1)
    baseline = float(np.asarray(explanation.base_values).reshape(-1)[0])
    st.dataframe(pd.DataFrame({"Feature": list(explanation.feature_names), "SHAP contribution": values})
                 .assign(_magnitude=np.abs(values)).sort_values("_magnitude", ascending=False).drop(columns="_magnitude"),
                 hide_index=True, width="stretch", column_config={"SHAP contribution": st.column_config.NumberColumn(format="%.6f", help="Positive raises the model output; negative lowers it. These are model contributions, not causal evidence.")})
    st.caption(f"Reference value {baseline:.6f} + total contribution {float(values.sum()):+.6f} = model output {baseline + float(values.sum()):.6f} ({explanation_output_unit(bundle)}).")


def explainability_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("SHAP shows how the fitted model uses each input when making a prediction. The global chart summarizes real contributions across a saved sample; the waterfall explains one recorded transaction. These are model explanations, not proof that a feature caused fraud.")
    heading("Explainability", "Every model decision should have a readable explanation.")
    from presentation_explain import explanation_for, global_explanation, reason_sentence, explanation_output_unit
    st.subheader("Global SHAP summary · what usually influences the model")
    explanation = global_explanation(bundle)
    _shap_figure(explanation, global_plot=True)
    with st.expander("Global feature influence · numerical summary"):
        st.dataframe(pd.DataFrame({"Feature": list(explanation.feature_names), "Mean absolute SHAP contribution": np.abs(explanation.values).mean(axis=0)})
                     .sort_values("Mean absolute SHAP contribution", ascending=False), hide_index=True, width="stretch")
    st.caption(f"Each dot is a genuine SHAP contribution for one saved explanatory-sample transaction. Red means a higher feature value and blue a lower value; dots to the right raise the fraud score. Displayed contribution units: {explanation_output_unit(bundle)}. This explanatory sample is not the full test evaluation population.")
    st.subheader("One transaction · step-by-step model reasoning")
    cases = _data(bundle, "demo_cases.csv")
    index = st.selectbox("Recorded transaction example", range(len(cases)), format_func=lambda value: f"Example {value + 1} · {TYPE_LABELS.get(cases.iloc[value]['type'], 'Transaction')} · amount {cases.iloc[value]['amount']:,.2f}", key="presentation_explanation_case")
    row = cases.iloc[int(index)]
    features = engineer_features(pd.DataFrame([row.loc[list(RAW_FIELDS)].to_dict()]))
    explanation = explanation_for(bundle, features)
    st.dataframe(friendly_frame(pd.DataFrame([row.loc[list(RAW_FIELDS)].to_dict()])), hide_index=True, width="stretch")
    scored = score_transactions(pd.DataFrame([row.loc[list(RAW_FIELDS)].to_dict()]), bundle).iloc[0]
    columns = st.columns(2)
    columns[0].metric("Model fraud probability", f"{float(scored['fraud_probability']):.2%}", help=TERM_GLOSSARY["Fraud probability"])
    columns[1].metric("Recorded dataset outcome", "Fraud" if int(row["isFraud"]) else "Legitimate", help="The actual label saved by the simulator for this unchanged recorded transaction. It is not used as an input to the classifier.")
    st.write("**In plain English:** " + reason_sentence(explanation, row))
    _shap_figure(explanation)
    st.caption(f"Start at the model's reference value, add the feature contributions, and arrive at its output. Red bars raise the score; blue bars lower it. Contribution units are {explanation_output_unit(bundle)}; log-odds are converted to the displayed probability by the model.")
    with st.expander("Per-transaction SHAP contributions · readable numbers"):
        shap_contribution_table(explanation, bundle)


def _set_live_case(cases: pd.DataFrame) -> None:
    row = cases.iloc[int(st.session_state["presentation_live_case"])]
    for feature in RAW_FIELDS:
        st.session_state[f"presentation_input_{feature}"] = str(row[feature]) if feature == "type" else int(row[feature]) if feature in ("step", "receiver_activity_count", "sender_transactions_24h") else float(row[feature])
    st.session_state.pop("presentation_prediction_result", None)


def _same_record(raw: pd.DataFrame, row: pd.Series) -> bool:
    return all(str(raw.iloc[0][name]) == str(row[name]) if name == "type" else float(raw.iloc[0][name]) == float(row[name]) for name in RAW_FIELDS)


def live_predictor_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("Enter readable transaction details and the model estimates its fraud risk using exactly the saved training features. Sender/receiver balances after the transaction make this a completed-payment check; activity counts would normally come from a banking system. A risk flag is a request for review, not a confirmed accusation or a safety guarantee.")
    heading("Live Predictor", "Readable inputs. A genuine prediction. Three understandable reasons.")
    cases = _data(bundle, "demo_cases.csv")
    if "presentation_live_case" not in st.session_state:
        legitimate = cases.index[(cases["isFraud"] == 0) & (cases["prediction"] == 0)].tolist()
        st.session_state["presentation_live_case"] = int(legitimate[0]) if legitimate else 0
        _set_live_case(cases)
    selected = st.selectbox("Start with a recorded example", range(len(cases)), format_func=lambda value: f"Example {value + 1} · {TYPE_LABELS.get(cases.iloc[value]['type'], 'Transaction')} · amount {cases.iloc[value]['amount']:,.2f}", key="presentation_live_case", on_change=_set_live_case, args=(cases,))
    row = cases.iloc[int(selected)]
    st.caption("You can replay a real saved example or edit its details to create a hypothetical transaction. The recorded label is revealed after analysis and only when every input is unchanged. PaySim amounts remain in the simulator's currency units.")
    with st.form("presentation_live_form"):
        columns = st.columns(2)
        values: dict[str, Any] = {}
        values["type"] = columns[0].selectbox(DISPLAY_NAMES["type"], ["PAYMENT", "TRANSFER", "CASH_OUT", "CASH_IN", "DEBIT"], format_func=lambda key: TYPE_LABELS[key], key="presentation_input_type", help=FEATURE_GLOSSARY["type"])
        values["amount"] = columns[1].number_input(DISPLAY_NAMES["amount"], min_value=0.0, step=100.0, format="%.2f", key="presentation_input_amount", help=FEATURE_GLOSSARY["amount"])
        st.markdown("**Balances before and after the transaction**")
        left, right = st.columns(2)
        for feature, column in (("oldbalanceOrg", left), ("newbalanceOrig", left), ("oldbalanceDest", right), ("newbalanceDest", right)):
            values[feature] = column.number_input(DISPLAY_NAMES[feature], min_value=0.0, step=100.0, format="%.2f", key=f"presentation_input_{feature}", help=FEATURE_GLOSSARY[feature])
        with st.expander("Timing and account activity · supplied by the banking system"):
            columns = st.columns(3)
            for feature, column in zip(("step", "receiver_activity_count", "sender_transactions_24h"), columns):
                values[feature] = column.number_input(DISPLAY_NAMES[feature], min_value=0, step=1, key=f"presentation_input_{feature}", help=FEATURE_GLOSSARY[feature])
            st.caption("Transaction Hour counts hours from the simulator's start. Hour of Day is that number modulo 24. There is no transaction-duration field. Activity counts describe strictly earlier transactions, not simultaneous or future payments.")
        submitted = st.form_submit_button("Analyze transaction", type="primary", width="stretch")
    if submitted:
        try:
            raw = pd.DataFrame([values], columns=list(RAW_FIELDS))
            scored = score_transactions(raw, bundle).iloc[0]
            from presentation_explain import explanation_for, reason_sentence
            features = engineer_features(raw)
            explanation = explanation_for(bundle, features)
            st.session_state["presentation_prediction_result"] = {
                "probability": float(scored["fraud_probability"]), "prediction": int(scored["prediction"]),
                "risk": str(scored["risk_level"]), "reason": reason_sentence(explanation, raw.iloc[0]),
                "features": features, "recorded": _same_record(raw, row), "actual": int(row["isFraud"]),
                "explanation": explanation,
            }
        except (ValueError, TypeError, KeyError, OSError) as exc:
            st.session_state.pop("presentation_prediction_result", None)
            st.error("This transaction could not be analyzed. Check that all balances and amounts are finite, nonnegative values, and that activity counts are whole numbers. Restore the matching model and explanation assets if the problem continues.")
    result = st.session_state.get("presentation_prediction_result")
    if result is None:
        st.info("Choose an example, check its details, and select Analyze transaction. No card number, password, or personal bank information is required.")
        return
    probability, risk = result["probability"], result["risk"]
    flagged = bool(result["prediction"])
    st.divider()
    st.markdown('<div class="risk-result ' + html.escape(risk.lower()) + '"><div class="eyebrow">' + html.escape(risk) + ' model-score band</div><strong>' + ("Flagged for review" if flagged else "Not flagged by the model") + '</strong><p>' + html.escape(result["reason"]) + '</p></div>', unsafe_allow_html=True)
    left, right = st.columns([1, 1.2])
    with left:
        chart = go.Figure(go.Indicator(mode="gauge+number", value=100 * probability, number=dict(suffix="%", font=dict(size=39)),
                                      title=dict(text="Model fraud probability", font=dict(size=15)),
                                      gauge=dict(axis=dict(range=[0, 100], tickvals=sorted(set([0, 50 * default_threshold(bundle), 100 * default_threshold(bundle), 100])), tickformat=".1f", ticksuffix="%"), bar=dict(color=ROSE if flagged else MINT), bgcolor="#111A2B", borderwidth=0,
                                                 steps=[dict(range=[0, 50 * default_threshold(bundle)], color="rgba(115,229,188,.13)"), dict(range=[50 * default_threshold(bundle), 100 * default_threshold(bundle)], color="rgba(165,148,255,.16)"), dict(range=[100 * default_threshold(bundle), 100], color="rgba(255,127,152,.14)")],
                                                 threshold=dict(line=dict(color=TEXT, width=2), value=100 * default_threshold(bundle)))))
        st.plotly_chart(style_chart(chart, 260), width="stretch", key="presentation_live_gauge")
    with right:
        st.metric("Review threshold", f"{default_threshold(bundle):.3%}", help="The deployed threshold was selected on validation data. A transaction is flagged when its score reaches this value; the High band begins here. Risk bands are a presentation policy, not calibrated real-world probabilities.")
        st.write(f"**Risk bands:** Low below {default_threshold(bundle) / 2:.2%}; Medium from {default_threshold(bundle) / 2:.2%} to below {default_threshold(bundle):.2%}; High at or above {default_threshold(bundle):.2%}. High means the saved review threshold was reached. These are presentation policy bands, not calibrated real-world risk categories.")
        st.caption("This is an uncalibrated model estimate on simulated data. A low score does not prove a payment is safe, and a high score does not prove fraud. The slider on Model Performance does not change this deployed prediction threshold.")
        if result["recorded"]:
            st.info("Recorded dataset outcome: " + ("Fraud" if result["actual"] else "Legitimate") + ". This unchanged example has a known simulator label; the classifier did not receive that label.")
        else:
            st.info("Hypothetical transaction: you changed the saved example. Its true fraud outcome is unknown; only the model's prediction can be shown.")
    with st.expander("Calculated model inputs · explained"):
        featured = result["features"].iloc[0]
        st.dataframe(pd.DataFrame([{"Model input": DISPLAY_NAMES[name], "Value": "Unavailable (zero starting balance)" if pd.isna(featured[name]) else TYPE_LABELS.get(str(featured[name]), str(featured[name])), "Meaning": FEATURE_GLOSSARY[name]} for name in FEATURES]), hide_index=True, width="stretch")
        st.caption("The transaction type is converted into separate yes/no indicators inside the saved preprocessing pipeline. Missing or zero sender balances follow the documented training formula for the percentage feature.")
    with st.expander("Show the real per-transaction SHAP waterfall"):
        _shap_figure(result["explanation"])
        shap_contribution_table(result["explanation"], bundle)


def methodology_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("This page explains the complete machine-learning experiment in simple terms, from source data to the deployed model. Training, validation, and testing happen in time order. The limitations are part of an honest academic presentation, including the fact that PaySim is a simulation of mobile-money transfers.")
    heading("Methodology", "A clear account of what was trained, how it was checked, and what it can prove.")
    metadata = bundle.metadata
    st.subheader("1 · Dataset and scope")
    st.write("**PaySim — Synthetic Financial Datasets For Fraud Detection.** A financial simulator generates legitimate mobile-money transactions and injected fraud scenarios. Synthetic data protects customer privacy and makes labelled examples available for research. It is not a real credit-card network dataset; this project uses it as an educational financial-fraud proxy under the submitted credit-card fraud detection topic.")
    st.markdown("[View the Kaggle dataset](https://www.kaggle.com/datasets/ealaxi/paysim1)")
    dataset, sampling = metadata["dataset"], metadata["sampling"]
    st.write(f"The verified source contains **{int(dataset.get('total_transactions', dataset.get('rows', 0))):,} transactions** and **{int(dataset['fraud_count']):,} fraud cases**. The project retains every fraud row and takes a deterministic, stratified legitimate sample to make an approximately **{int(sampling['rows']):,}-row** research dataset. Stratification respects transaction type and time periods; this is not an ordinary random sample at the natural fraud rate.")
    st.subheader("2 · Feature engineering and leakage prevention")
    st.write("Sender and receiver identifiers are used only to calculate earlier activity counts, then removed. The simulator's existing fraud-alert field is removed too, so the model cannot copy another system's alert. The recorded Fraud / Legitimate label is the training target and never a prediction input.")
    with st.expander("Source columns removed from the model · what they meant"):
        st.dataframe(pd.DataFrame([
            {"Source column": "Sender Account", "Meaning": "The sender's simulated account identifier.", "Why removed": "Used to calculate earlier sender activity, then excluded so the classifier cannot memorize account identifiers."},
            {"Source column": "Receiver Account", "Meaning": "The receiver's simulated account identifier.", "Why removed": "Used to calculate earlier receiving activity, then excluded from model inputs."},
            {"Source column": "Existing Rule Flag", "Meaning": "A simulator rule's existing suspicious-transfer alert.", "Why removed": "The project learns its own decision rather than relying on another system's pre-existing alert."},
        ]), hide_index=True, width="stretch")
    st.write("All activity counts use strictly earlier transactions. Payments in the same recorded hour are excluded from each other's counts because their order within that hour is unknown. Receiver Activity Count counts earlier arrivals; Sender Transactions in Last 24h counts earlier sender activity within the previous 24 simulated hours.")
    formulas = [
        ("sender_debited", "Sender Balance Before − Sender Balance After"),
        ("receiver_credited", "Receiver Balance After − Receiver Balance Before"),
        ("sender_mismatch", "Sender Balance Before − Transaction Amount − Sender Balance After"),
        ("receiver_mismatch", "Receiver Balance Before + Transaction Amount − Receiver Balance After"),
        ("account_emptied", "Yes when Sender Balance After is zero and the amount is at least 95% of Sender Balance Before"),
        ("amount_pct_sender_balance", "Transaction Amount as a percentage of Sender Balance Before; see the feature glossary for zero-balance handling"),
        ("hour_of_day", "Transaction Hour modulo 24"),
    ]
    st.dataframe(pd.DataFrame([{"Feature": DISPLAY_NAMES[key], "Calculation": formula, "Plain meaning": FEATURE_GLOSSARY[key]} for key, formula in formulas]), hide_index=True, width="stretch")
    st.info("There is no transaction-duration field in PaySim. Timing is represented by Hour of Day and sender activity, not by how long a payment took.")
    st.write("Numeric missing values use medians learned only from training data. Transaction Type is one-hot encoded. Logistic Regression also scales the numeric features; tree models use numeric values directly. The saved joblib pipeline contains the complete preprocessing and feature order.")
    st.subheader("3 · A split that respects time")
    split = metadata["split"]
    rows = []
    for key in ("train", "validation", "test"):
        part = split.get(key, {})
        rows.append({"Period": key.title(), "Source transactions": part.get("rows", "See saved metadata"),
                     "Recorded fraud": part.get("fraud_count", part.get("fraud", "See saved metadata")),
                     "First transaction hour": split.get(key + "_step_min", part.get("step_min", "—")),
                     "Last transaction hour": split.get(key + "_step_max", part.get("step_max", "—"))})
    st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch")
    st.write("Earlier hours train the models. Middle hours choose the best model and its fraud-score threshold. Later hours measure performance. The boundaries never split the same simulated hour between periods. The full validation and test populations retain their natural class imbalance; headline test results are not calculated on the fraud-enriched sample.")
    st.subheader("4 · Three models and class-imbalance handling")
    for name in ("Logistic Regression", "Random Forest", "XGBoost"):
        st.write(f"**{name}:** {TERM_GLOSSARY[name]}")
    st.write("Rare fraud cases receive extra influence during training through class weights or the boosting model's fraud-class weight. Every fraud row remains in its chronological period; later fraud cases never enter earlier training. No fabricated fraud rows or blanket SMOTE resampling are used.")
    st.write(f"**Selected model: {metadata['selected_model']}.** Candidates are compared on validation data. Their decision thresholds are selected there as well. After selection, each candidate is measured on the same complete later test period. The Model Performance slider is an educational exploration of that fixed test set.")
    st.subheader("5 · Explainability and evaluation")
    st.write("Precision measures useful alerts; recall measures fraud caught; F1 balances them. PR-AUC is the trapezoidal area under the precision–recall curve, while average precision is a separate step-wise summary. ROC-AUC measures ranking. A confusion matrix reports actual false alarms and missed fraud. Accuracy is secondary because legitimate transactions dominate the source.")
    st.write("True SHAP values explain the fitted model globally and for each checked transaction. The feature names are translated into plain English without changing the trained model. SHAP contributions describe model behavior; they do not establish a causal explanation for fraud.")
    with st.expander("Important limitations to explain in a presentation", expanded=True):
        st.write("• PaySim simulates mobile-money fraud rather than real credit-card authorizations. Good simulated results do not establish performance at a real bank.")
        st.write("• Balances after a payment make this a retrospective transaction check. They cannot usually be entered truthfully before a card payment is authorized.")
        st.write("• Amount, sender debit and mismatch formulas work most directly for outgoing transaction types. Deposits and some merchant records have different balance semantics; an unavailable receiver balance is not itself proof of fraud.")
        st.write("• Activity counts may have little variation because many simulated accounts appear only once. They are measured context, not an invented behavioral history.")
        st.write("• Fraud-enriched training changes the observed class rate. The displayed model probability has not been separately calibrated to deployment prevalence.")
        st.write("• Fraud patterns can change over time. A real service would need monitoring, access controls, bank-side account context, and human verification before action.")
        for text in metadata.get("limitations", []):
            readable = str(text).replace("isFlaggedFraud", "Existing Rule Flag").replace("nameOrig", "Sender Account").replace("nameDest", "Receiver Account")
            for raw_name in sorted(DISPLAY_NAMES, key=len, reverse=True):
                # Metadata prose can contain a source key; keep these technical
                # keys out of the presentation even when a bundle is upgraded.
                if raw_name not in ("type", "amount", "step", "prediction", "outcome"):
                    readable = readable.replace(raw_name, DISPLAY_NAMES[raw_name])
            st.write("• " + readable)
    st.caption("Academic topics demonstrated: EDA, feature engineering, categorical encoding, scaling, imbalanced classification, time-based splitting, model comparison, threshold selection, evaluation, SHAP, reusable model pipelines, and Streamlit deployment.")


def glossary_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("Use this page to explain every input, derived feature, and ML term without jargon. The names match the charts, tables, and SHAP explanations. The dataset's technical column names stay inside the code.")
    heading("Glossary", "A plain-English reference for the whole project.")
    st.subheader("Transaction columns and calculated features")
    st.dataframe(pd.DataFrame([{"Column or feature": DISPLAY_NAMES.get(key, key), "Plain meaning": meaning} for key, meaning in FEATURE_GLOSSARY.items() if key in DISPLAY_NAMES]), hide_index=True, width="stretch")
    st.subheader("Machine-learning terms")
    for term, explanation in TERM_GLOSSARY.items():
        with st.expander(term):
            st.write(explanation)
    st.caption("Money is shown in PaySim's simulated currency units. Transaction Hour measures elapsed simulated hours; Hour of Day is derived from that counter and is not a measured payment duration.")


def card_payment_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("This preserved page demonstrates the earlier, separate Sparkov credit-card model using payment details and strictly earlier card history. Its dataset, fitted model, scores, and recorded labels are separate from PaySim. Use it to show the difference between a card-history approach and a completed-transfer balance approach.")
    st.info("Separate credit-card research model · Sparkov data. The PaySim model and Model Performance threshold do not control this page.")
    from card_dashboard import artifact_directory as card_directory, cached_bundle as card_bundle, cached_records, file_signature as card_signature, payment_page
    directory = card_directory()
    saved = card_bundle(str(directory), card_signature(directory, ("metadata.json", "model.pkl")))
    cases = cached_records(str(directory / "demo_cases.csv"), card_signature(directory, ("demo_cases.csv",)), demo=True)
    history = cached_records(str(directory / "account_history.csv"), card_signature(directory, ("account_history.csv",)))
    payment_page(saved, cases, history)


def card_results_tab(bundle: PresentationBundle) -> None:
    what_am_i_looking_at("These are the preserved measured results for the separate Sparkov credit-card model. It uses spending history and its own chronological train, validation, and test periods. None of these numbers are PaySim results, and the two datasets are not merged.")
    st.info("Separate credit-card research model · Sparkov data. For the new PaySim experiment, use Model Performance and Methodology.")
    from card_dashboard import artifact_directory as card_directory, cached_bundle as card_bundle, file_signature as card_signature, performance_page
    directory = card_directory()
    saved = card_bundle(str(directory), card_signature(directory, ("metadata.json", "model.pkl")))
    performance_page(saved)


def main() -> None:
    st.set_page_config(page_title="CreditVault | Fraud Detection ML Project", page_icon="💳", layout="wide", initial_sidebar_state="auto")
    css_path = ROOT / "assets" / "dashboard.css"
    css = css_path.read_text(encoding="utf-8") if css_path.is_file() else ""
    # The retained card pages share their original scoped styles without starting
    # a second Streamlit app or changing its model configuration.
    from card_dashboard import CARD_CSS
    st.markdown(f"<style>{css}{CARD_CSS}{PRESENTATION_CSS}</style>", unsafe_allow_html=True)
    with st.sidebar:
        st.markdown('<div class="brand">CreditVault<small>EXPLAINABLE FRAUD DETECTION</small></div>', unsafe_allow_html=True)
        st.caption("An ML project you can demonstrate and explain, one clear page at a time.")
        st.markdown('<div class="sidebar-note"><span>PRIMARY EXPERIMENT</span><strong>PaySim · simulated finance</strong><p>Readable balance and activity features.<br>Time-based evaluation.<br>Genuine SHAP explanations.</p></div>', unsafe_allow_html=True)
    directory = artifact_directory()
    try:
        bundle = cached_bundle(str(directory), file_signature(directory, ("metadata.json", "model.pkl")))
    except (OSError, ValueError, TypeError, KeyError, RuntimeError) as exc:
        st.title("Credit Card Fraud Detection System")
        st.error("The trained presentation model could not be loaded. Restore the complete presentation_artifacts folder and install the exact requirements, then restart the app.")
        return
    with st.sidebar:
        st.divider()
        st.caption(f"Loaded model: {bundle.metadata['selected_model']}")
        st.caption(f"Review threshold: {default_threshold(bundle):.6f}")
        st.markdown('<div class="sidebar-note"><strong>Academic demonstration</strong><p>Simulated data, not a bank connection.<br>A fraud flag means review.<br>Scores are not safety guarantees.</p></div>', unsafe_allow_html=True)
    st.markdown('<div class="app-topbar"><div class="wordmark">CreditVault / ML presentation</div><span class="status-badge">Trained model loaded</span></div>', unsafe_allow_html=True)
    renderers = (overview_tab, data_explorer_tab, model_performance_tab, explainability_tab,
                 live_predictor_tab, methodology_tab, glossary_tab, card_payment_tab, card_results_tab)
    containers = st.tabs(TABS, key="presentation_tab", on_change="rerun", bind="query-params")
    # Native lazy tabs keep the 500k-row explorer and SHAP plots out of the
    # initial render. Tab selection is bookmarkable and keyboard accessible.
    for container, renderer in zip(containers, renderers):
        if container.open:
            with container:
                try:
                    renderer(bundle)
                except (OSError, ValueError, TypeError, KeyError, RuntimeError, ImportError) as exc:
                    st.error("This page's saved data or explanation assets could not be loaded. Restore the matching presentation export and requirements. Other tabs remain available.")


if __name__ == "__main__":
    main()
