[theme]
base = "dark"
primaryColor = "#73E5BC"
backgroundColor = "#080D18"
secondaryBackgroundColor = "#111A2B"
textColor = "#E7EEF8"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
